server:
  port: 9090
spring:
  mvc:
    view:
      suffix: .html
      prefix: /
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:productDb;DB_CLOSE_DELAY=-1
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop  profiles:    active: dev 
management:
  endpoints:
    web:
      exposure:
        include: '*'

greetProp: "Hello {will not be read}"      
